export type BadgeRarity = "common" | "rare" | "epic" | "legendary" | "secret";
export type BadgeCategory = "words" | "streak" | "lessons" | "xp" | "games" | "ai" | "secrets";

export interface BadgeDefinition {
  id: string;
  rarity: BadgeRarity;
  category: BadgeCategory;
  titleEn: string;
  titleRu: string;
  titleUa: string;
  descEn: string;
  descRu: string;
  descUa: string;
  secretDescEn?: string;
  secretDescRu?: string;
  secretDescUa?: string;
  icon: string;
  target?: number;
  xpReward: number;
}

export const RARITY_CONFIG: Record<BadgeRarity, {
  labelUa: string;
  labelRu: string;
  labelEn: string;
  color: string;
  bg: string;
  border: string;
  shadow: string;
  gradient: string;
}> = {
  common: {
    labelUa: "Звичайне",
    labelRu: "Обычное",
    labelEn: "Common",
    color: "text-slate-400 dark:text-slate-300",
    bg: "bg-slate-500/10",
    border: "border-slate-400/30",
    shadow: "shadow-slate-500/10",
    gradient: "from-slate-500/20 to-slate-700/10",
  },
  rare: {
    labelUa: "Рідкісне",
    labelRu: "Редкое",
    labelEn: "Rare",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/40",
    shadow: "shadow-blue-500/20",
    gradient: "from-blue-600/20 via-cyan-500/15 to-blue-900/10",
  },
  epic: {
    labelUa: "Епічне",
    labelRu: "Эпическое",
    labelEn: "Epic",
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    border: "border-purple-500/50",
    shadow: "shadow-purple-500/30",
    gradient: "from-purple-600/25 via-pink-500/20 to-indigo-900/15",
  },
  legendary: {
    labelUa: "Легендарне",
    labelRu: "Легендарное",
    labelEn: "Legendary",
    color: "text-amber-400 font-extrabold",
    bg: "bg-amber-500/15",
    border: "border-amber-400/60",
    shadow: "shadow-amber-500/40 shadow-lg",
    gradient: "from-amber-500/30 via-yellow-500/20 to-orange-600/20",
  },
  secret: {
    labelUa: "Секретне",
    labelRu: "Секретное",
    labelEn: "Secret",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    border: "border-rose-500/40",
    shadow: "shadow-rose-500/30",
    gradient: "from-rose-950/40 via-purple-950/30 to-black/40",
  },
};

export const BADGE_DEFINITIONS: Record<string, BadgeDefinition> = {
  // --- WORDS & VOCABULARY ---
  words_1: {
    id: "words_1",
    rarity: "common",
    category: "words",
    titleEn: "First Word",
    titleRu: "Первое слово",
    titleUa: "Перше слово",
    descEn: "Learned your first Croatian word",
    descRu: "Выучил своё первое хорватское слово",
    descUa: "Вивчив своє перше хорватське слово",
    icon: "🌱",
    target: 1,
    xpReward: 25,
  },
  words_10: {
    id: "words_10",
    rarity: "common",
    category: "words",
    titleEn: "First Steps",
    titleRu: "Первые шаги",
    titleUa: "Перші кроки",
    descEn: "Learned 10 Croatian words",
    descRu: "Выучил 10 хорватских слов",
    descUa: "Вивчив 10 хорватських слів",
    icon: "🌿",
    target: 10,
    xpReward: 50,
  },
  words_25: {
    id: "words_25",
    rarity: "common",
    category: "words",
    titleEn: "Green Sprout",
    titleRu: "Зеленый росток",
    titleUa: "Зелений паросток",
    descEn: "Learned 25 vocabulary words",
    descRu: "Выучил 25 хорватских слов",
    descUa: "Вивчив 25 хорватських слів",
    icon: "🍀",
    target: 25,
    xpReward: 75,
  },
  words_50: {
    id: "words_50",
    rarity: "common",
    category: "words",
    titleEn: "Young Scholar",
    titleRu: "Юный языковед",
    titleUa: "Юний мовознавець",
    descEn: "Learned 50 vocabulary words",
    descRu: "Выучил 50 хорватских слов",
    descUa: "Вивчив 50 хорватських слів",
    icon: "📖",
    target: 50,
    xpReward: 100,
  },
  words_100: {
    id: "words_100",
    rarity: "rare",
    category: "words",
    titleEn: "First Hundred",
    titleRu: "Первая сотня",
    titleUa: "Перша сотня",
    descEn: "Learned 100 Croatian vocabulary words",
    descRu: "Выучил 100 хорватских слов",
    descUa: "Вивчив 100 хорватських слів",
    icon: "📚",
    target: 100,
    xpReward: 200,
  },
  words_200: {
    id: "words_200",
    rarity: "rare",
    category: "words",
    titleEn: "Confident Speaker",
    titleRu: "Уверенный собеседник",
    titleUa: "Впевнений співрозмовник",
    descEn: "Mastered 200 Croatian words",
    descRu: "Освоил 200 хорватских слов",
    descUa: "Опанував 200 хорватських слів",
    icon: "💬",
    target: 200,
    xpReward: 300,
  },
  words_350: {
    id: "words_350",
    rarity: "rare",
    category: "words",
    titleEn: "Vocabulary Boost",
    titleRu: "Словарный бафф",
    titleUa: "Словниковий баф",
    descEn: "Learned 350 active words",
    descRu: "Выучил 350 активных слов",
    descUa: "Вивчив 350 активних слів",
    icon: "🧠",
    target: 350,
    xpReward: 400,
  },
  words_500: {
    id: "words_500",
    rarity: "epic",
    category: "words",
    titleEn: "Master of Words",
    titleRu: "Мастер слов",
    titleUa: "Майстер слів",
    descEn: "Mastered 500 Croatian vocabulary words",
    descRu: "Освоил 500 хорватских слов",
    descUa: "Опанував 500 хорватських слів",
    icon: "👑",
    target: 500,
    xpReward: 600,
  },
  words_750: {
    id: "words_750",
    rarity: "epic",
    category: "words",
    titleEn: "Polyglot Novice",
    titleRu: "Полиглот новичок",
    titleUa: "Поліглот початківець",
    descEn: "Expanded vocabulary to 750 words",
    descRu: "Расширил словарь до 750 слов",
    descUa: "Розширив словник до 750 слів",
    icon: "💡",
    target: 750,
    xpReward: 800,
  },
  words_1000: {
    id: "words_1000",
    rarity: "epic",
    category: "words",
    titleEn: "Vocabulary Giant",
    titleRu: "Словарный гигант",
    titleUa: "Словниковий гігант",
    descEn: "Accumulated 1,000 mastered words",
    descRu: "Собрал 1,000 выученных слов",
    descUa: "Зібрав 1,000 вивчених слів",
    icon: "🏛️",
    target: 1000,
    xpReward: 1000,
  },
  words_1500: {
    id: "words_1500",
    rarity: "legendary",
    category: "words",
    titleEn: "Lexicon Professor",
    titleRu: "Профессор лексики",
    titleUa: "Професор лексики",
    descEn: "Mastered 1,500 Croatian vocabulary words",
    descRu: "Освоил 1,500 хорватских слов",
    descUa: "Опанував 1,500 хорватських слів",
    icon: "🔮",
    target: 1500,
    xpReward: 1500,
  },
  words_2000: {
    id: "words_2000",
    rarity: "legendary",
    category: "words",
    titleEn: "Living Dictionary",
    titleRu: "Живой словарь",
    titleUa: "Живий словник",
    descEn: "Mastered 2,000 words in Croatian",
    descRu: "Освоил 2,000 хорватских слов",
    descUa: "Опанував 2,000 хорватських слів",
    icon: "⚡",
    target: 2000,
    xpReward: 2000,
  },
  words_3000: {
    id: "words_3000",
    rarity: "legendary",
    category: "words",
    titleEn: "Croatian Encyclopedia",
    titleRu: "Хорватская энциклопедия",
    titleUa: "Хорватська енциклопедія",
    descEn: "Mastered 3,000+ words — Fluent Vocabulary",
    descRu: "Освоил 3,000+ слов — Полная свобода речи",
    descUa: "Опанував 3,000+ слів — Повна свобода мови",
    icon: "🌌",
    target: 3000,
    xpReward: 3000,
  },
  flashcards_10: {
    id: "flashcards_10",
    rarity: "common",
    category: "words",
    titleEn: "Card Player",
    titleRu: "Карточный игрок",
    titleUa: "Карточний гравець",
    descEn: "Practiced 10 flashcard sessions",
    descRu: "Прошёл 10 карточек слов",
    descUa: "Пройшов 10 карток слів",
    icon: "🎴",
    target: 10,
    xpReward: 50,
  },
  flashcards_50: {
    id: "flashcards_50",
    rarity: "rare",
    category: "words",
    titleEn: "Anki Master",
    titleRu: "Мастер Anki",
    titleUa: "Майстер Anki",
    descEn: "Completed 50 active recall flashcard sessions",
    descRu: "Завершил 50 сессий карточек с интервальным повторением",
    descUa: "Завершив 50 сесій карток з інтервальним повторенням",
    icon: "🎴",
    target: 50,
    xpReward: 150,
  },
  flashcards_200: {
    id: "flashcards_200",
    rarity: "epic",
    category: "words",
    titleEn: "Card Shuffler",
    titleRu: "Тасовщик карт",
    titleUa: "Тасовщик карт",
    descEn: "Completed 200 flashcard repetitions",
    descRu: "Прошёл 200 карточек слов",
    descUa: "Пройшов 200 карток слів",
    icon: "🃏",
    target: 200,
    xpReward: 400,
  },
  flashcards_500: {
    id: "flashcards_500",
    rarity: "legendary",
    category: "words",
    titleEn: "Lord of Cards",
    titleRu: "Властелин карт",
    titleUa: "Властелин карт",
    descEn: "Completed 500 flashcard active recall reviews",
    descRu: "Прошёл 500 карточек слов",
    descUa: "Пройшов 500 карток слів",
    icon: "🔮",
    target: 500,
    xpReward: 1000,
  },
  quiz_perfect: {
    id: "quiz_perfect",
    rarity: "rare",
    category: "words",
    titleEn: "Perfect Score Quiz",
    titleRu: "100% Результат",
    titleUa: "100% Результат",
    descEn: "Scored 100% in a custom vocabulary quiz",
    descRu: "Получил 100% в словарном тесте без ошибок",
    descUa: "Отримав 100% у словниковому тесті без помилок",
    icon: "🎯",
    xpReward: 200,
  },

  // --- STREAKS & HABITS ---
  streak_1: {
    id: "streak_1",
    rarity: "common",
    category: "streak",
    titleEn: "Spark of Learning",
    titleRu: "Искра обучения",
    titleUa: "Іскра навчання",
    descEn: "Started your daily streak",
    descRu: "Начал свой первый ударный день",
    descUa: "Розпочав свій перший ударний день",
    icon: "🕯️",
    target: 1,
    xpReward: 25,
  },
  streak_3: {
    id: "streak_3",
    rarity: "common",
    category: "streak",
    titleEn: "First Flame",
    titleRu: "Первое пламя",
    titleUa: "Перше полум'я",
    descEn: "Maintained a 3-day active streak",
    descRu: "Удерживал 3 дня ударного режима",
    descUa: "Утримував 3 дні ударного режиму",
    icon: "💥",
    target: 3,
    xpReward: 50,
  },
  streak_5: {
    id: "streak_5",
    rarity: "common",
    category: "streak",
    titleEn: "Work Week Streak",
    titleRu: "Рабочая неделя",
    titleUa: "Робочий тиждень",
    descEn: "Maintained a 5-day active learning streak",
    descRu: "Удерживал 5 дней подряд",
    descUa: "Утримував 5 днів поспіль",
    icon: "⚡",
    target: 5,
    xpReward: 75,
  },
  streak_7: {
    id: "streak_7",
    rarity: "rare",
    category: "streak",
    titleEn: "Streak Warrior",
    titleRu: "7 дней подряд",
    titleUa: "7 днів поспіль",
    descEn: "Maintained a 7-day learning streak",
    descRu: "Удерживал 7-дневный ударный режим",
    descUa: "Утримував 7-денний ударний режим",
    icon: "🔥",
    target: 7,
    xpReward: 150,
  },
  streak_10: {
    id: "streak_10",
    rarity: "rare",
    category: "streak",
    titleEn: "10-Day Stability",
    titleRu: "10 Дней стабильности",
    titleUa: "10 Днів стабільності",
    descEn: "Reached 10 consecutive active learning days",
    descRu: "Достиг 10 дней активного обучения",
    descUa: "Досяг 10 днів активного навчання",
    icon: "🚀",
    target: 10,
    xpReward: 200,
  },
  streak_14: {
    id: "streak_14",
    rarity: "rare",
    category: "streak",
    titleEn: "Fortnight Fort",
    titleRu: "Двухнедельный форт",
    titleUa: "Двотижневий форт",
    descEn: "Reached 14 consecutive active learning days",
    descRu: "Достиг 14 дней ударного режима",
    descUa: "Досяг 14 днів ударного режиму",
    icon: "🛡️",
    target: 14,
    xpReward: 300,
  },
  streak_21: {
    id: "streak_21",
    rarity: "epic",
    category: "streak",
    titleEn: "Habit Formed",
    titleRu: "Привычка сформирована",
    titleUa: "Звичка сформована",
    descEn: "Maintained a 21-day learning streak",
    descRu: "Удерживал 21 день подряд — привычка вошла в жизнь",
    descUa: "Утримував 21 день поспіль — звичка стала частиною життя",
    icon: "🧘",
    target: 21,
    xpReward: 500,
  },
  streak_30: {
    id: "streak_30",
    rarity: "epic",
    category: "streak",
    titleEn: "Unstoppable Legend",
    titleRu: "30 дней подряд",
    titleUa: "30 днів поспіль",
    descEn: "Achieved a 30-day active learning streak",
    descRu: "Достиг 30-дневного ударного режима",
    descUa: "Досяг 30-денного ударного режиму",
    icon: "🌕",
    target: 30,
    xpReward: 750,
  },
  streak_45: {
    id: "streak_45",
    rarity: "epic",
    category: "streak",
    titleEn: "Fire Titan",
    titleRu: "Огненный титан",
    titleUa: "Вогняний титан",
    descEn: "Maintained a 45-day active learning streak",
    descRu: "Удерживал 45 дней подряд",
    descUa: "Утримував 45 днів поспіль",
    icon: "🌋",
    target: 45,
    xpReward: 1000,
  },
  streak_60: {
    id: "streak_60",
    rarity: "legendary",
    category: "streak",
    titleEn: "Two Months Flame",
    titleRu: "Двухмесячное пламя",
    titleUa: "Двомісячне полум'я",
    descEn: "Maintained a 60-day active learning streak",
    descRu: "Удерживал 60 дней подряд",
    descUa: "Утримував 60 днів поспіль",
    icon: "☀️",
    target: 60,
    xpReward: 1500,
  },
  streak_90: {
    id: "streak_90",
    rarity: "legendary",
    category: "streak",
    titleEn: "Quarter Champion",
    titleRu: "Квартал победителя",
    titleUa: "Квартал переможця",
    descEn: "Achieved 90 consecutive active learning days",
    descRu: "Достиг 90 дней подряд (3 месяца)",
    descUa: "Досяг 90 днів поспіль (3 місяці)",
    icon: "🏆",
    target: 90,
    xpReward: 2000,
  },
  streak_180: {
    id: "streak_180",
    rarity: "legendary",
    category: "streak",
    titleEn: "Half-Year Legend",
    titleRu: "Полгода несокрушимости",
    titleUa: "Півроку незламності",
    descEn: "Maintained 180 consecutive active learning days",
    descRu: "Удерживал 180 дней подряд",
    descUa: "Утримував 180 днів поспіль",
    icon: "🛡️",
    target: 180,
    xpReward: 3500,
  },
  streak_365: {
    id: "streak_365",
    rarity: "legendary",
    category: "streak",
    titleEn: "365-Day Immortal",
    titleRu: "365 Дней бессмертия",
    titleUa: "365 Днів безсмертя",
    descEn: "Achieved a 1-Year unbroken active streak",
    descRu: "Достиг целого года без единого пропуска",
    descUa: "Досяг цілого року без жодного пропуску",
    icon: "🌌",
    target: 365,
    xpReward: 5000,
  },
  weekend_hero: {
    id: "weekend_hero",
    rarity: "rare",
    category: "streak",
    titleEn: "Weekend Hero",
    titleRu: "Герой выходных",
    titleUa: "Герой вихідних",
    descEn: "Studied on both Saturday and Sunday",
    descRu: "Учился и в субботу, и в воскресенье",
    descUa: "Навчався і в суботу, і в неділю",
    icon: "🏖️",
    xpReward: 150,
  },
  early_bird: {
    id: "early_bird",
    rarity: "rare",
    category: "streak",
    titleEn: "Early Bird",
    titleRu: "Утренняя птичка",
    titleUa: "Ранкова пташка",
    descEn: "Completed a lesson before 8:00 AM",
    descRu: "Пройти урок раньше 8:00 утра",
    descUa: "Пройти урок раніше 8:00 ранку",
    icon: "🌅",
    xpReward: 150,
  },
  night_owl: {
    id: "night_owl",
    rarity: "rare",
    category: "streak",
    titleEn: "Night Owl",
    titleRu: "Ночная сова",
    titleUa: "Нічний сова",
    descEn: "Completed a lesson after 11:00 PM",
    descRu: "Пройти урок после 23:00 вечера",
    descUa: "Пройти урок після 23:00 вечора",
    icon: "🌙",
    xpReward: 150,
  },

  // --- LESSONS & CEFR LEVELS ---
  lesson_1: {
    id: "lesson_1",
    rarity: "common",
    category: "lessons",
    titleEn: "First Step Lesson",
    titleRu: "Первый урок",
    titleUa: "Перший урок",
    descEn: "Completed your first lesson module",
    descRu: "Завершил свой первый модуль урока",
    descUa: "Завершив свій перший модуль уроку",
    icon: "📖",
    target: 1,
    xpReward: 30,
  },
  lesson_3: {
    id: "lesson_3",
    rarity: "common",
    category: "lessons",
    titleEn: "Path Begun",
    titleRu: "Начало пути",
    titleUa: "Початок шляху",
    descEn: "Completed 3 lessons",
    descRu: "Завершил 3 урока",
    descUa: "Завершив 3 уроки",
    icon: "✏️",
    target: 3,
    xpReward: 60,
  },
  lesson_5: {
    id: "lesson_5",
    rarity: "common",
    category: "lessons",
    titleEn: "Student Badge",
    titleRu: "Ученический стаж",
    titleUa: "Учневий стаж",
    descEn: "Completed 5 lessons in total",
    descRu: "Завершил 5 уроков",
    descUa: "Завершив 5 уроків",
    icon: "📑",
    target: 5,
    xpReward: 100,
  },
  lesson_10: {
    id: "lesson_10",
    rarity: "rare",
    category: "lessons",
    titleEn: "Topic Scholar",
    titleRu: "Знаток тем",
    titleUa: "Знавець тем",
    descEn: "Completed 10 full lessons",
    descRu: "Завершил 10 полноценных уроков",
    descUa: "Завершив 10 повноцінних уроків",
    icon: "🎒",
    target: 10,
    xpReward: 200,
  },
  lesson_20: {
    id: "lesson_20",
    rarity: "rare",
    category: "lessons",
    titleEn: "Honor Student",
    titleRu: "Заслуженный ученик",
    titleUa: "Заслужений учень",
    descEn: "Completed 20 lessons",
    descRu: "Завершил 20 уроков",
    descUa: "Завершив 20 уроків",
    icon: "📜",
    target: 20,
    xpReward: 400,
  },
  lesson_35: {
    id: "lesson_35",
    rarity: "epic",
    category: "lessons",
    titleEn: "Lesson Academic",
    titleRu: "Академик уроков",
    titleUa: "Академік уроків",
    descEn: "Completed 35 modules across levels",
    descRu: "Пройшёл 35 обучающих модулей",
    descUa: "Пройшов 35 навчальних модулів",
    icon: "🎓",
    target: 35,
    xpReward: 700,
  },
  lesson_50: {
    id: "lesson_50",
    rarity: "legendary",
    category: "lessons",
    titleEn: "Grand Master of Lessons",
    titleRu: "Великий Магистр",
    titleUa: "Великий Магістр",
    descEn: "Completed 50 lessons — Complete Course Mastery",
    descRu: "Завершил 50 уроков — Полный курс пройдён",
    descUa: "Завершив 50 уроків — Повний курс пройдено",
    icon: "🏛️",
    target: 50,
    xpReward: 1500,
  },
  level_a1: {
    id: "level_a1",
    rarity: "common",
    category: "lessons",
    titleEn: "Beginner A1",
    titleRu: "Новичок A1",
    titleUa: "Початківець A1",
    descEn: "Reached CEFR Level A1",
    descRu: "Достиг уровня A1 (Начальный)",
    descUa: "Досяг рівня A1 (Початковий)",
    icon: "🟢",
    xpReward: 100,
  },
  level_a2: {
    id: "level_a2",
    rarity: "rare",
    category: "lessons",
    titleEn: "Elementary A2",
    titleRu: "Базовый A2",
    titleUa: "Базовий A2",
    descEn: "Reached CEFR Level A2",
    descRu: "Достиг уровня A2 (Элементарный)",
    descUa: "Досяг рівня A2 (Елементарний)",
    icon: "🔵",
    xpReward: 250,
  },
  level_b1: {
    id: "level_b1",
    rarity: "epic",
    category: "lessons",
    titleEn: "Intermediate B1",
    titleRu: "Средний B1",
    titleUa: "Середній B1",
    descEn: "Reached CEFR Level B1",
    descRu: "Достиг уровня B1 (Средний)",
    descUa: "Досяг рівня B1 (Середній)",
    icon: "🟣",
    xpReward: 500,
  },
  level_b2: {
    id: "level_b2",
    rarity: "epic",
    category: "lessons",
    titleEn: "Upper Intermediate B2",
    titleRu: "Продвинутый B2",
    titleUa: "Просунутий B2",
    descEn: "Reached CEFR Level B2",
    descRu: "Достиг уровня B2 (Выше среднего)",
    descUa: "Досяг рівня B2 (Вище середнього)",
    icon: "🟣",
    xpReward: 750,
  },
  level_c1: {
    id: "level_c1",
    rarity: "legendary",
    category: "lessons",
    titleEn: "Advanced C1",
    titleRu: "Профессионал C1",
    titleUa: "Професіонал C1",
    descEn: "Reached CEFR Level C1",
    descRu: "Достиг уровня C1 (Профессиональный)",
    descUa: "Досяг рівня C1 (Професійний)",
    icon: "🟡",
    xpReward: 1200,
  },
  level_c2: {
    id: "level_c2",
    rarity: "legendary",
    category: "lessons",
    titleEn: "Native Mastery C2",
    titleRu: "Носитель C2",
    titleUa: "Носій C2",
    descEn: "Achieved Master CEFR Level C2",
    descRu: "Достиг уровня C2 (Владение в совершенстве)",
    descUa: "Досяг рівня C2 (Вільне володіння)",
    icon: "👑",
    xpReward: 2500,
  },
  grammar_1: {
    id: "grammar_1",
    rarity: "common",
    category: "lessons",
    titleEn: "Grammar Basics",
    titleRu: "Знаток падежей",
    titleUa: "Знавець відмінків",
    descEn: "Completed a Croatian grammar lesson module",
    descRu: "Завершил грамматический урок",
    descUa: "Завершив граматичний урок",
    icon: "📝",
    xpReward: 50,
  },
  reading_1: {
    id: "reading_1",
    rarity: "common",
    category: "lessons",
    titleEn: "Text Reader",
    titleRu: "Читатель текстов",
    titleUa: "Читач текстів",
    descEn: "Completed a Croatian reading text lesson",
    descRu: "Завершил урок по чтению хорватских текстов",
    descUa: "Завершив урок з читання хорватських текстів",
    icon: "👓",
    xpReward: 50,
  },
  dictation_1: {
    id: "dictation_1",
    rarity: "rare",
    category: "lessons",
    titleEn: "Listener",
    titleRu: "Слушатель речи",
    titleUa: "Слухач мови",
    descEn: "Completed 1 audio dictation exercise",
    descRu: "Пройшел 1 аудирование и диктант",
    descUa: "Пройшов 1 аудіювання та диктант",
    icon: "🎧",
    target: 1,
    xpReward: 100,
  },
  dictation_5: {
    id: "dictation_5",
    rarity: "epic",
    category: "lessons",
    titleEn: "Audio Sniper",
    titleRu: "Аудио снайпер",
    titleUa: "Аудіо снайпер",
    descEn: "Completed 5 listening & dictation exercises",
    descRu: "Пройшел 5 аудирований и диктантов",
    descUa: "Пройшов 5 аудіювань та диктантів",
    icon: "🎯",
    target: 5,
    xpReward: 400,
  },
  dialogue_master: {
    id: "dialogue_master",
    rarity: "rare",
    category: "lessons",
    titleEn: "Dialogue Master",
    titleRu: "Мастер диалогов",
    titleUa: "Майстер діалогів",
    descEn: "Completed a real-world dialogue lesson scenario",
    descRu: "Завершил практический диалоговый урок",
    descUa: "Завершив практичний діалоговий урок",
    icon: "💬",
    xpReward: 150,
  },

  // --- XP & EXPERIENCE ---
  xp_50: {
    id: "xp_50",
    rarity: "common",
    category: "xp",
    titleEn: "First XP",
    titleRu: "Первый опыт",
    titleUa: "Перший досвід",
    descEn: "Accumulated 50 total XP points",
    descRu: "Набрал первые 50 XP",
    descUa: "Набрав перші 50 XP",
    icon: "🌱",
    target: 50,
    xpReward: 25,
  },
  xp_250: {
    id: "xp_250",
    rarity: "common",
    category: "xp",
    titleEn: "Light of Knowledge",
    titleRu: "Свет знаний",
    titleUa: "Світло знань",
    descEn: "Accumulated 250 XP",
    descRu: "Набрал 250 XP",
    descUa: "Набрав 250 XP",
    icon: "✨",
    target: 250,
    xpReward: 50,
  },
  xp_500: {
    id: "xp_500",
    rarity: "common",
    category: "xp",
    titleEn: "500 XP Milestone",
    titleRu: "Пятьсот XP",
    titleUa: "П'ятьсот XP",
    descEn: "Accumulated 500 XP",
    descRu: "Набрал 500 XP",
    descUa: "Набрав 500 XP",
    icon: "🌟",
    target: 500,
    xpReward: 100,
  },
  xp_1000: {
    id: "xp_1000",
    rarity: "rare",
    category: "xp",
    titleEn: "XP Legend",
    titleRu: "Тысячник",
    titleUa: "Тисячник",
    descEn: "Accumulated 1,000+ total XP points",
    descRu: "Заработал более 1000 XP",
    descUa: "Заробив понад 1000 XP",
    icon: "⭐",
    target: 1000,
    xpReward: 200,
  },
  xp_2500: {
    id: "xp_2500",
    rarity: "rare",
    category: "xp",
    titleEn: "Starlight Collector",
    titleRu: "Звездный сбор",
    titleUa: "Зоряний збір",
    descEn: "Accumulated 2,500 total XP points",
    descRu: "Набрал 2500 XP",
    descUa: "Набрав 2500 XP",
    icon: "💫",
    target: 2500,
    xpReward: 350,
  },
  xp_5000: {
    id: "xp_5000",
    rarity: "epic",
    category: "xp",
    titleEn: "XP Accumulator",
    titleRu: "Накопитель XP",
    titleUa: "Накопичувач XP",
    descEn: "Accumulated 5,000 total XP points",
    descRu: "Набрал 5000 XP",
    descUa: "Набрав 5000 XP",
    icon: "🔮",
    target: 5000,
    xpReward: 600,
  },
  xp_10000: {
    id: "xp_10000",
    rarity: "epic",
    category: "xp",
    titleEn: "Ten-Thousander",
    titleRu: "Десятитысячник",
    titleUa: "Десятитисячник",
    descEn: "Accumulated 10,000 total XP points",
    descRu: "Преодолел отметку 10,000 XP",
    descUa: "Подолав позначку 10,000 XP",
    icon: "💎",
    target: 10000,
    xpReward: 1000,
  },
  xp_25000: {
    id: "xp_25000",
    rarity: "legendary",
    category: "xp",
    titleEn: "Experience Mage",
    titleRu: "Маг опыта",
    titleUa: "Маг досвіду",
    descEn: "Accumulated 25,000 total XP points",
    descRu: "Заработал 25,000 XP",
    descUa: "Заробив 25,000 XP",
    icon: "👑",
    target: 25000,
    xpReward: 2000,
  },
  xp_50000: {
    id: "xp_50000",
    rarity: "legendary",
    category: "xp",
    titleEn: "Cosmic XP",
    titleRu: "Космический XP",
    titleUa: "Космічний XP",
    descEn: "Accumulated 50,000 total XP points",
    descRu: "Достиг 50,000 XP",
    descUa: "Досяг 50,000 XP",
    icon: "🌌",
    target: 50000,
    xpReward: 3500,
  },
  xp_100000: {
    id: "xp_100000",
    rarity: "legendary",
    category: "xp",
    titleEn: "100K Titan",
    titleRu: "Стотысячный титан",
    titleUa: "Стотисячний титан",
    descEn: "Accumulated 100,000 total XP points",
    descRu: "Достиг феноменальных 100,000 XP",
    descUa: "Досяг феноменальних 100,000 XP",
    icon: "🌠",
    target: 100000,
    xpReward: 5000,
  },
  daily_xp_100: {
    id: "daily_xp_100",
    rarity: "rare",
    category: "xp",
    titleEn: "Daily Sprint",
    titleRu: "Дневной спринт",
    titleUa: "Денний спринт",
    descEn: "Earned 100+ XP in a single day",
    descRu: "Заработал 100+ XP за один день",
    descUa: "Заробив 100+ XP за один день",
    icon: "🚀",
    target: 100,
    xpReward: 100,
  },
  daily_xp_300: {
    id: "daily_xp_300",
    rarity: "epic",
    category: "xp",
    titleEn: "Daily Lightning",
    titleRu: "Дневная молния",
    titleUa: "Денна блискавка",
    descEn: "Earned 300+ XP in a single day",
    descRu: "Заработал 300+ XP за один день",
    descUa: "Заробив 300+ XP за один день",
    icon: "⚡",
    target: 300,
    xpReward: 250,
  },
  daily_xp_500: {
    id: "daily_xp_500",
    rarity: "legendary",
    category: "xp",
    titleEn: "Daily Eruption",
    titleRu: "Дневной вулкан",
    titleUa: "Денний вулкан",
    descEn: "Earned 500+ XP in a single day",
    descRu: "Заработал 500+ XP за один день",
    descUa: "Заробив 500+ XP за один день",
    icon: "🌋",
    target: 500,
    xpReward: 500,
  },
  leaderboard_top10: {
    id: "leaderboard_top10",
    rarity: "rare",
    category: "xp",
    titleEn: "Top 10 Scholar",
    titleRu: "ТОП-10 Лидеров",
    titleUa: "ТОП-10 Лідерів",
    descEn: "Entered the Top 10 in community leaderboard",
    descRu: "Вошёл в ТОП-10 таблицы лидеров",
    descUa: "Увійшов до ТОП-10 таблиці лідерів",
    icon: "🏆",
    xpReward: 200,
  },
  leaderboard_top3: {
    id: "leaderboard_top3",
    rarity: "epic",
    category: "xp",
    titleEn: "Podium Finish",
    titleRu: "Подиум почета",
    titleUa: "Подіум пошани",
    descEn: "Reached Top 3 on the leaderboard",
    descRu: "Занял место на подиуме (ТОП-3) лидеров",
    descUa: "Зайняв місце на подіумі (ТОП-3) лідерів",
    icon: "🥈",
    xpReward: 500,
  },
  leaderboard_top1: {
    id: "leaderboard_top1",
    rarity: "legendary",
    category: "xp",
    titleEn: "#1 Champion",
    titleRu: "Чемпион недели",
    titleUa: "Чемпіон тижня",
    descEn: "Ranked #1 on the overall leaderboard",
    descRu: "Занял 1-е место в общем рейтинге учеников",
    descUa: "Зайняв 1-ше місце в загальному рейтингу учнів",
    icon: "🥇",
    xpReward: 1000,
  },

  // --- GAMES & MINI-GAMES ---
  game_first: {
    id: "game_first",
    rarity: "common",
    category: "games",
    titleEn: "First Gamer",
    titleRu: "Первый игроман",
    titleUa: "Перший ігроман",
    descEn: "Played your first mini-game",
    descRu: "Сыграл в свою первую мини-игру со словами",
    descUa: "Зіграв у свою першу міні-гру зі словами",
    icon: "🎮",
    target: 1,
    xpReward: 30,
  },
  game_5: {
    id: "game_5",
    rarity: "common",
    category: "games",
    titleEn: "Game Lover",
    titleRu: "Азартный ученик",
    titleUa: "Азартний учень",
    descEn: "Played 5 mini-games",
    descRu: "Сыграл в 5 мини-игр",
    descUa: "Зіграв у 5 міні-ігор",
    icon: "🎯",
    target: 5,
    xpReward: 75,
  },
  game_25: {
    id: "game_25",
    rarity: "rare",
    category: "games",
    titleEn: "Croatian Gamer",
    titleRu: "Геймер хорватского",
    titleUa: "Геймер хорватської",
    descEn: "Completed 25 mini-games",
    descRu: "Завершил 25 обучающих мини-игр",
    descUa: "Завершив 25 навчальних міні-ігор",
    icon: "🕹️",
    target: 25,
    xpReward: 200,
  },
  game_100: {
    id: "game_100",
    rarity: "epic",
    category: "games",
    titleEn: "Cyber Student",
    titleRu: "Кибер-студент",
    titleUa: "Кібер-студент",
    descEn: "Completed 100 mini-game sessions",
    descRu: "Сыграл в 100 мини-игр со словами",
    descUa: "Зіграв у 100 міні-ігор зі словами",
    icon: "👾",
    target: 100,
    xpReward: 600,
  },
  speed_quiz_1: {
    id: "speed_quiz_1",
    rarity: "common",
    category: "games",
    titleEn: "Speed Quiz Novice",
    titleRu: "Быстрый спринтер",
    titleUa: "Швидкий спринтер",
    descEn: "Played a Speed Quiz round",
    descRu: "Пройшел раунд Спид-Квиза",
    descUa: "Пройшов раунд Спід-Квізу",
    icon: "⚡",
    xpReward: 50,
  },
  speed_quiz_perfect: {
    id: "speed_quiz_perfect",
    rarity: "epic",
    category: "games",
    titleEn: "Lightning Mind",
    titleRu: "Молниеносный ум",
    titleUa: "Блискавичний розум",
    descEn: "Completed a Speed Quiz without missing a word",
    descRu: "Пройшел Спид-Квиз без единой ошибки",
    descUa: "Пройшов Спід-Квіз без жодної помилки",
    icon: "⚡",
    xpReward: 300,
  },
  hangman_win: {
    id: "hangman_win",
    rarity: "common",
    category: "games",
    titleEn: "Hangman Hero",
    titleRu: "Спаситель слов",
    titleUa: "Рятівник слів",
    descEn: "Won a game of Croatian Hangman",
    descRu: "Угадал слово в игре Виселица",
    descUa: "Вгадав слово в грі Шибениця",
    icon: "🪢",
    xpReward: 50,
  },
  hangman_5: {
    id: "hangman_5",
    rarity: "rare",
    category: "games",
    titleEn: "Hangman Master",
    titleRu: "Мастер Виселицы",
    titleUa: "Майстер Шибениці",
    descEn: "Won 5 games of Croatian Hangman",
    descRu: "Выиграл 5 раз в Виселицу",
    descUa: "Виграв 5 разів у Шибеницю",
    icon: "🪢",
    target: 5,
    xpReward: 150,
  },
  scramble_1: {
    id: "scramble_1",
    rarity: "common",
    category: "games",
    titleEn: "Scramble Solver",
    titleRu: "Анаграмма разгадана",
    titleUa: "Анаграма розгадана",
    descEn: "Solved a Word Scramble puzzle",
    descRu: "Розгадал анаграмму слова",
    descUa: "Розгадав анаграму слова",
    icon: "🧩",
    xpReward: 50,
  },
  scramble_10: {
    id: "scramble_10",
    rarity: "rare",
    category: "games",
    titleEn: "Puzzle Master",
    titleRu: "Словарный пазл",
    titleUa: "Словниковий пазл",
    descEn: "Solved 10 Word Scramble puzzles",
    descRu: "Разгадал 10 анаграмм сведений",
    descUa: "Розгадав 10 анаграм слів",
    icon: "🧩",
    target: 10,
    xpReward: 150,
  },
  listening_1: {
    id: "listening_1",
    rarity: "common",
    category: "games",
    titleEn: "Good Ear",
    titleRu: "Ухо разведчика",
    titleUa: "Вухо розвідника",
    descEn: "Completed a Listening Comprehension game",
    descRu: "Завершил игру на восприятие речи на слух",
    descUa: "Завершив гру на сприйняття мови на слух",
    icon: "🎧",
    xpReward: 50,
  },
  fill_blanks_1: {
    id: "fill_blanks_1",
    rarity: "common",
    category: "games",
    titleEn: "Blank Filler",
    titleRu: "Заполнитель пропусков",
    titleUa: "Заповнювач пропусків",
    descEn: "Completed a Fill in the Blanks game",
    descRu: "Заполнил пропуски в предложении",
    descUa: "Заповнив пропуски в реченні",
    icon: "✍️",
    xpReward: 50,
  },
  audio_spelling_1: {
    id: "audio_spelling_1",
    rarity: "rare",
    category: "games",
    titleEn: "Audio Spellcheck",
    titleRu: "Аудио-спикер",
    titleUa: "Аудіо-спікер",
    descEn: "Completed an Audio Spelling session",
    descRu: "Написал слово на слух без ошибок",
    descUa: "Написав слово на слух без помилок",
    icon: "🔊",
    xpReward: 100,
  },
  word_match_1: {
    id: "word_match_1",
    rarity: "common",
    category: "games",
    titleEn: "Matchmaker",
    titleRu: "Парный мастер",
    titleUa: "Парний майстер",
    descEn: "Completed a Word Match session",
    descRu: "Сопоставил пары слов",
    descUa: "Зіставив пари слів",
    icon: "🔗",
    xpReward: 50,
  },
  word_match_fast: {
    id: "word_match_fast",
    rarity: "epic",
    category: "games",
    titleEn: "Speed Matcher",
    titleRu: "Скоростная пара",
    titleUa: "Швидкісна пара",
    descEn: "Matched all pairs in under 30 seconds",
    descRu: "Сопоставил все пары быстрее чем за 30 секунд",
    descUa: "Зіставив усі пари швидше ніж за 30 секунд",
    icon: "⏱️",
    xpReward: 300,
  },
  all_games_tried: {
    id: "all_games_tried",
    rarity: "epic",
    category: "games",
    titleEn: "All Games Player",
    titleRu: "Игровой универсал",
    titleUa: "Ігровий універсал",
    descEn: "Played every mini-game mode available",
    descRu: "Сыграл во все доступные типы игр",
    descUa: "Зіграв у всі доступні типи ігор",
    icon: "🌟",
    xpReward: 500,
  },
  game_win_streak_5: {
    id: "game_win_streak_5",
    rarity: "epic",
    category: "games",
    titleEn: "Win Streak 5",
    titleRu: "Серия побед 5",
    titleUa: "Серія перемог 5",
    descEn: "Won 5 games in a row",
    descRu: "Выиграл 5 игр подряд без поражений",
    descUa: "Виграв 5 ігор поспіль без поразок",
    icon: "🏆",
    target: 5,
    xpReward: 400,
  },
  game_win_streak_10: {
    id: "game_win_streak_10",
    rarity: "legendary",
    category: "games",
    titleEn: "Undefeated Master",
    titleRu: "Непобедимый",
    titleUa: "Непереможний",
    descEn: "Won 10 consecutive games",
    descRu: "Выиграл 10 игр подряд — Непобедимая серия!",
    descUa: "Виграв 10 ігор поспіль — Непереможна серія!",
    icon: "👑",
    target: 10,
    xpReward: 1000,
  },

  // --- AI MENTOR & PRACTICE ---
  ai_first: {
    id: "ai_first",
    rarity: "common",
    category: "ai",
    titleEn: "AI Greeting",
    titleRu: "Знакомство с ИИ",
    titleUa: "Знайомство з ШІ",
    descEn: "Sent your first message to AI Mentor",
    descRu: "Отправил первое сообщение ИИ-наставнику",
    descUa: "Надіслав перше повідомлення ШІ-наставнику",
    icon: "🤖",
    target: 1,
    xpReward: 30,
  },
  ai_messages_10: {
    id: "ai_messages_10",
    rarity: "common",
    category: "ai",
    titleEn: "AI Conversationalist",
    titleRu: "Собеседник ИИ",
    titleUa: "Співрозмовник ШІ",
    descEn: "Exchanged 10 messages with AI Mentor",
    descRu: "Обменялся 10 сообщениями с ИИ",
    descUa: "Обмінявся 10 повідомленнями з ШІ",
    icon: "💬",
    target: 10,
    xpReward: 75,
  },
  ai_messages_50: {
    id: "ai_messages_50",
    rarity: "rare",
    category: "ai",
    titleEn: "Deep Thinker",
    titleRu: "Интеллектуальный диалог",
    titleUa: "Інтелектуальний діалог",
    descEn: "Exchanged 50 messages with AI Mentor",
    descRu: "Провел 50 сообщений диалога с ИИ",
    descUa: "Провів 50 повідомлень діалогу з ШІ",
    icon: "🧠",
    target: 50,
    xpReward: 250,
  },
  ai_messages_100: {
    id: "ai_messages_100",
    rarity: "epic",
    category: "ai",
    titleEn: "Friend of AI",
    titleRu: "Друг ИИ",
    titleUa: "Друг ШІ",
    descEn: "Exchanged 100 messages with AI Mentor",
    descRu: "Написал 100 сообщений виртуальному наставнику",
    descUa: "Написав 100 повідомлень віртуальному наставнику",
    icon: "🤖",
    target: 100,
    xpReward: 500,
  },
  ai_messages_250: {
    id: "ai_messages_250",
    rarity: "legendary",
    category: "ai",
    titleEn: "Language Cyborg",
    titleRu: "Языковой киборг",
    titleUa: "Мовний кіборг",
    descEn: "Exchanged 250 messages with AI Mentor",
    descRu: "Провел 250 сообщений практики диалога с ИИ",
    descUa: "Провів 250 повідомлень практики діалогу з ШІ",
    icon: "🔮",
    target: 250,
    xpReward: 1200,
  },
  ai_grammar_ask: {
    id: "ai_grammar_ask",
    rarity: "common",
    category: "ai",
    titleEn: "Curious Mind",
    titleRu: "Любопытный ум",
    titleUa: "Допитливий розум",
    descEn: "Asked AI to explain a grammar rule",
    descRu: "Попросил ИИ объяснить грамматическое правило",
    descUa: "Попросив ШІ пояснити граматичне правило",
    icon: "❓",
    xpReward: 50,
  },
  ai_correction_fix: {
    id: "ai_correction_fix",
    rarity: "rare",
    category: "ai",
    titleEn: "Error Fixed",
    titleRu: "Работа над ошибками",
    titleUa: "Робота над помилками",
    descEn: "Corrected a Croatian sentence with AI guidance",
    descRu: "Исправил ошибку в предложении благодаря подсказке ИИ",
    descUa: "Виправив помилку в реченні завдяки підказці ШІ",
    icon: "🛠️",
    xpReward: 150,
  },
  ai_roleplay_complete: {
    id: "ai_roleplay_complete",
    rarity: "epic",
    category: "ai",
    titleEn: "Roleplay Master",
    titleRu: "Актер ролевой игры",
    titleUa: "Актор рольової гри",
    descEn: "Completed a simulated roleplay (Cafe, Hotel, Airport)",
    descRu: "Пройшел симуляцию диалога (Кафе, Отель или Аэропорт)",
    descUa: "Пройшов симуляцію діалогу (Кафе, Готель або Аеропорт)",
    icon: "🎭",
    xpReward: 350,
  },

  // --- SECRET & HIDDEN EASTER EGGS ---
  secret_night_study: {
    id: "secret_night_study",
    rarity: "secret",
    category: "secrets",
    titleEn: "Night Academic",
    titleRu: "Ночной академик",
    titleUa: "Нічний академік",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Studied Croatian between 2:00 AM and 4:00 AM",
    secretDescRu: "Учился хорватскому в глухую ночь между 2:00 и 4:00 утра",
    secretDescUa: "Навчався хорватській мові у глибині ночі між 2:00 та 4:00 ранку",
    icon: "👁️‍🗨️",
    xpReward: 300,
  },
  secret_first_day: {
    id: "secret_first_day",
    rarity: "secret",
    category: "secrets",
    titleEn: "Pioneer Learner",
    titleRu: "Первопроходец",
    titleUa: "Першопроходець",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Joined Croatia Mentor and completed first test on registration day",
    secretDescRu: "Зарегистрировался и сразу прошёл вводный тест в 1-й день",
    secretDescUa: "Зареєструвався та одразу пройшов вступний тест у 1-й день",
    icon: "🚀",
    xpReward: 200,
  },
  secret_profile_avatar: {
    id: "secret_profile_avatar",
    rarity: "secret",
    category: "secrets",
    titleEn: "Style Icon",
    titleRu: "Стильный образ",
    titleUa: "Стильний образ",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Changed profile avatar icon 3 times",
    secretDescRu: "Сменил аватар профиля 3 раза",
    secretDescUa: "Змінив аватар профілю 3 рази",
    icon: "🎨",
    xpReward: 150,
  },
  secret_phoenix: {
    id: "secret_phoenix",
    rarity: "secret",
    category: "secrets",
    titleEn: "Phoenix Risen",
    titleRu: "Феникс из пепла",
    titleUa: "Фенікс з попелу",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Reset progress and started fresh with renewed determination",
    secretDescRu: "Сбросил прогресс и начал путь заново с чистым разумом",
    secretDescUa: "Скинув прогрес та розпочав шлях наново з чистим розумом",
    icon: "🔥",
    xpReward: 500,
  },
  secret_clicker: {
    id: "secret_clicker",
    rarity: "secret",
    category: "secrets",
    titleEn: "Curious Clicker",
    titleRu: "Любопытный кликер",
    titleUa: "Допитливий клікер",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Clicked on achievement badges 10 times in excitement",
    secretDescRu: "Кликнул по карточкам достижений 10 раз",
    secretDescUa: "Клікнув по картках досягнень 10 разів",
    icon: "🖱️",
    xpReward: 100,
  },
  secret_polyglot: {
    id: "secret_polyglot",
    rarity: "secret",
    category: "secrets",
    titleEn: "Language Switcher",
    titleRu: "Переводчик миров",
    titleUa: "Перекладач світів",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Switched interface language between UA, RU, and EN",
    secretDescRu: "Переключил язык интерфейса платформы",
    secretDescUa: "Переключив мову інтерфейсу платформи",
    icon: "🌐",
    xpReward: 150,
  },
  secret_perfect_streak: {
    id: "secret_perfect_streak",
    rarity: "secret",
    category: "secrets",
    titleEn: "Perfect Week",
    titleRu: "Идеальная неделя",
    titleUa: "Ідеальний тиждень",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Completed all 7 daily quest wizards in a single week",
    secretDescRu: "Выполнил все 7 пошаговых дневных квестов за неделю",
    secretDescUa: "Виконав усі 7 покрокових денних квестів за тиждень",
    icon: "✨",
    xpReward: 350,
  },
  secret_vocab_speed: {
    id: "secret_vocab_speed",
    rarity: "secret",
    category: "secrets",
    titleEn: "Vocabulary Speedster",
    titleRu: "Скоростной словарь",
    titleUa: "Швидкісний словник",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Learned 20 new words in a single day",
    secretDescRu: "Выучил 20 новых слов за один день",
    secretDescUa: "Вивчив 20 нових слів за один день",
    icon: "⚡",
    xpReward: 300,
  },
  secret_test_master: {
    id: "secret_test_master",
    rarity: "secret",
    category: "secrets",
    titleEn: "Test Phenomenon",
    titleRu: "Тестовый феномен",
    titleUa: "Тестовий феномен",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Scored 90%+ on Level Placement Test",
    secretDescRu: "Набрал 90%+ в тесте определения уровня",
    secretDescUa: "Набрав 90%+ у тесті визначення рівня",
    icon: "🎯",
    xpReward: 400,
  },
  secret_marathon: {
    id: "secret_marathon",
    rarity: "secret",
    category: "secrets",
    titleEn: "Study Marathoner",
    titleRu: "Марафонец знаний",
    titleUa: "Марафонець знань",
    descEn: "??? (Hidden Secret Badge)",
    descRu: "??? (Скрытое секретное достижение)",
    descUa: "??? (Приховане секретне досягнення)",
    secretDescEn: "Spent 30+ minutes learning in a single day session",
    secretDescRu: "Занимался обучением 30+ минут за один день",
    secretDescUa: "Займався навчанням 30+ хвилин за один день",
    icon: "🏃",
    xpReward: 350,
  },
};
