export interface BlankSentence {
  id: string;
  text: string; // use ___ for blank
  options: string[];
  correctAnswer: string;
  translation: { en: string; ru: string; ua: string };
  level: "A1" | "A2" | "B1" | "B2";
  category: "verbs" | "cases" | "pronouns" | "prepositions" | "vocabulary";
}

export const fillBlanksData: BlankSentence[] = [
  // A1 VERBS & PRESENT TENSE (1-20)
  {
    id: "fb-1",
    text: "Ja ___ student i studiram u Zagrebu.",
    options: ["sam", "si", "je", "smo"],
    correctAnswer: "sam",
    translation: { en: "I am a student and I study in Zagreb.", ru: "Я студент и учусь в Загребе.", ua: "Я студент і навчаюся в Загребі." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-2",
    text: "Ona ___ u velikom stanu.",
    options: ["živi", "živim", "živiš", "žive"],
    correctAnswer: "živi",
    translation: { en: "She lives in a big apartment.", ru: "Она живет в большой квартире.", ua: "Вона живе у великій квартирі." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-3",
    text: "Mi ___ crnu kavu ujutro.",
    options: ["pijemo", "pijem", "piješ", "piju"],
    correctAnswer: "pijemo",
    translation: { en: "We drink black coffee in the morning.", ru: "Мы пьем черный кофе по утрам.", ua: "Ми п'ємо чорну каву вранці." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-4",
    text: "Oni ___ hrvatski vrlo dobro.",
    options: ["govore", "govorim", "govoriš", "govori"],
    correctAnswer: "govore",
    translation: { en: "They speak Croatian very well.", ru: "Они говорят по-хорватски очень хорошо.", ua: "Вони говорять хорватською дуже добре." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-5",
    text: "Ti ___ u restoranu svaku večer.",
    options: ["radiš", "radim", "radi", "radimo"],
    correctAnswer: "radiš",
    translation: { en: "You work at a restaurant every evening.", ru: "Ты работаешь в ресторане каждый вечер.", ua: "Ти працюєш у ресторані щовечора." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-6",
    text: "Vi ___ u hotelu pokraj mora.",
    options: ["spavate", "spavam", "spava", "spavaju"],
    correctAnswer: "spavate",
    translation: { en: "You all sleep in a hotel by the sea.", ru: "Вы спите в отеле у моря.", ua: "Ви спите в готелі біля моря." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-7",
    text: "Marko ___ novu knjigu.",
    options: ["čita", "čitam", "čitaš", "čitaju"],
    correctAnswer: "čita",
    translation: { en: "Marko is reading a new book.", ru: "Марко читает новую книгу.", ua: "Марко читає нову книгу." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-8",
    text: "Djeca ___ u parku poslije škole.",
    options: ["se igraju", "se igram", "se igraš", "se igra"],
    correctAnswer: "se igraju",
    translation: { en: "Children play in the park after school.", ru: "Дети играют в парке после школы.", ua: "Діти граються в парку після школи." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-9",
    text: "Svako jutro ___ ukusan doručak.",
    options: ["jedem", "jedeš", "jede", "jedemo"],
    correctAnswer: "jedem",
    translation: { en: "Every morning I eat a delicious breakfast.", ru: "Каждое утро я ем вкусный завтрак.", ua: "Щоранку я їм смачний сніданок." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-10",
    text: "Danas ___ automobilom u grad.",
    options: ["putujemo", "putujem", "putuješ", "putuju"],
    correctAnswer: "putujemo",
    translation: { en: "Today we travel by car to the city.", ru: "Сегодня мы едем на машине в город.", ua: "Сьогодні ми їдемо машиною в місто." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-11",
    text: "Ana ___ u trgovini.",
    options: ["kupuje", "kupujem", "kupuješ", "kupuju"],
    correctAnswer: "kupuje",
    translation: { en: "Ana buys in the store.", ru: "Ана покупает в магазине.", ua: "Ана купує в магазині." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-12",
    text: "Moja sestra ___ na sveučilištu.",
    options: ["uči", "učim", "učiš", "uče"],
    correctAnswer: "uči",
    translation: { en: "My sister studies at university.", ru: "Моя сестра учится в университете.", ua: "Моя сестра навчається в університеті." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-13",
    text: "Ljeti rado ___ u čistom moru.",
    options: ["plivam", "plivaš", "pliva", "plivamo"],
    correctAnswer: "plivam",
    translation: { en: "In summer I love to swim in clean sea.", ru: "Летом я с удовольствием плаваю в чистом море.", ua: "Влітку я із задоволенням плаваю в чистому морі." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-14",
    text: "Profesor ___ novu lekciju.",
    options: ["objašnjava", "objašnjavam", "objašnjavaš", "objašnjavaju"],
    correctAnswer: "objašnjava",
    translation: { en: "Teacher explains new lesson.", ru: "Учитель объясняет новый урок.", ua: "Вчитель пояснює новий урок." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-15",
    text: "Moja baka ___ ukusan kolač.",
    options: ["peče", "pečem", "pečeš", "peku"],
    correctAnswer: "peče",
    translation: { en: "My grandmother bakes a tasty cake.", ru: "Моя бабушка печет вкусный пирог.", ua: "Моя бабуся пече смачний пиріг." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-16",
    text: "Srećko ___ čašu hladne vode.",
    options: ["traži", "tražim", "tražiš", "traže"],
    correctAnswer: "traži",
    translation: { en: "Srećko asks for a glass of cold water.", ru: "Сречко ищет стакан холодной воды.", ua: "Сречко шукає склянку холодної води." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-17",
    text: "Kada ___ vlak za Split?",
    options: ["polazi", "polazim", "polaziš", "polaze"],
    correctAnswer: "polazi",
    translation: { en: "When does train depart for Split?", ru: "Когда уходит поезд в Сплит?", ua: "Коли відходить потяг до Спліта?" },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-18",
    text: "Mi se ___ u osam sati ujutro.",
    options: ["budimo", "budim", "budiš", "bude"],
    correctAnswer: "budimo",
    translation: { en: "We wake up at eight o'clock in morning.", ru: "Мы просыпаемся в восемь утра.", ua: "Ми прокидаємося о восьмій ранку." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-19",
    text: "Oni ___ autobus na stanici.",
    options: ["čekaju", "čekam", "čekaš", "čeka"],
    correctAnswer: "čekaju",
    translation: { en: "They are waiting for bus at station.", ru: "Они ждут автобус на остановке.", ua: "Вони чекають на автобус на зупинці." },
    level: "A1",
    category: "verbs",
  },
  {
    id: "fb-20",
    text: "Večeras ___ omiljeni film.",
    options: ["gledam", "gledaš", "gleda", "gledamo"],
    correctAnswer: "gledam",
    translation: { en: "Tonight I am watching favorite movie.", ru: "Сегодня вечером я смотрю любимый фильм.", ua: "Сьогодні ввечері я дивлюся улюблений фільм." },
    level: "A1",
    category: "verbs",
  },

  // QUESTION WORDS & PRONOUNS (21-40)
  {
    id: "fb-21",
    text: "___ se zoveš? - Zovem se Ivan.",
    options: ["Kako", "Što", "Gdje", "Kada"],
    correctAnswer: "Kako",
    translation: { en: "What is your name? - My name is Ivan.", ru: "Как тебя зовут? - Меня зовут Иван.", ua: "Як тебе звати? - Мене звати Іван." },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-22",
    text: "___ živiš? - Živim u Rijeci.",
    options: ["Gdje", "Kako", "Što", "Tko"],
    correctAnswer: "Gdje",
    translation: { en: "Where do you live? - I live in Rijeka.", ru: "Где ты живешь? - Я живу в Риеке.", ua: "Де ти живеш? - Я живу в Рієці." },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-23",
    text: "___ je to na stolu? - To je moja torba.",
    options: ["Što", "Tko", "Gdje", "Zašto"],
    correctAnswer: "Što",
    translation: { en: "What is that on the table? - That is my bag.", ru: "Что это на столе? - Это моя сумка.", ua: "Що це на столі? - Це моя сумка." },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-24",
    text: "___ je taj čovjek? - To je naš profesor.",
    options: ["Tko", "Što", "Gdje", "Kada"],
    correctAnswer: "Tko",
    translation: { en: "Who is that man? - That is our professor.", ru: "Кто этот человек? - Это наш профессор.", ua: "Хто ця людина? - Це наш професор." },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-25",
    text: "___ košta ova kava? - Dvije kune.",
    options: ["Koliko", "Kako", "Gdje", "Zašto"],
    correctAnswer: "Koliko",
    translation: { en: "How much does this coffee cost?", ru: "Сколько стоит этот кофе?", ua: "Скільки коштує ця кава?" },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-26",
    text: "___ dolaziš na zabavu? - Oko osam.",
    options: ["Kada", "Zašto", "Gdje", "Kako"],
    correctAnswer: "Kada",
    translation: { en: "When are you coming to party?", ru: "Когда ты придешь на вечеринку?", ua: "Коли ти прийдеш на вечірку?" },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-27",
    text: "___ ne spavaš? - Zato što učim.",
    options: ["Zašto", "Gdje", "Tko", "Što"],
    correctAnswer: "Zašto",
    translation: { en: "Why are you not sleeping?", ru: "Почему ты не спишь?", ua: "Чому ти не спиш?" },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-28",
    text: "Ovo je ___ pas, zove se Reks.",
    options: ["moj", "moja", "moje", "moji"],
    correctAnswer: "moj",
    translation: { en: "This is my dog, his name is Rex.", ru: "Это моя собака, её зовут Рекс.", ua: "Це мій собака, його звати Рекс." },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-29",
    text: "To je ___ obitelj na fotografiji.",
    options: ["naša", "naš", "naše", "naši"],
    correctAnswer: "naša",
    translation: { en: "That is our family in photograph.", ru: "Это наша семья на фотографии.", ua: "Це наша сім'я на фотографії." },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-30",
    text: "Gledam ___ novu kuću.",
    options: ["njihovu", "njihov", "njihovo", "njihovi"],
    correctAnswer: "njihovu",
    translation: { en: "I am looking at their new house.", ru: "Я смотрю на их новый дом.", ua: "Я дивлюся на їхній новий будинок." },
    level: "A2",
    category: "pronouns",
  },
  {
    id: "fb-31",
    text: "___ je sestra mlada i lijepa.",
    options: ["Tvoja", "Tvoj", "Tvoje", "Tvoji"],
    correctAnswer: "Tvoja",
    translation: { en: "Your sister is young and beautiful.", ru: "Твоя сестра молодая и красивая.", ua: "Твоя сестра молода і красива." },
    level: "A1",
    category: "pronouns",
  },
  {
    id: "fb-32",
    text: "Meni se ___ priča sviđa.",
    options: ["ova", "ovaj", "ovo", "ovi"],
    correctAnswer: "ova",
    translation: { en: "I like this story.", ru: "Мне нравится эта история.", ua: "Мені подобається ця історія." },
    level: "A2",
    category: "pronouns",
  },
  {
    id: "fb-33",
    text: "On ___ daje svoj broj telefona.",
    options: ["joj", "ju", "nje", "njoj"],
    correctAnswer: "joj",
    translation: { en: "He gives her his phone number.", ru: "Он дает ей свой номер телефона.", ua: "Він дає їй свій номер телефону." },
    level: "A2",
    category: "pronouns",
  },
  {
    id: "fb-34",
    text: "Reci ___ istinu odmah!",
    options: ["mi", "me", "moj", "mene"],
    correctAnswer: "mi",
    translation: { en: "Tell me the truth right away!", ru: "Скажи мне правду прямо сейчас!", ua: "Скажи мені правду просто зараз!" },
    level: "A2",
    category: "pronouns",
  },
  {
    id: "fb-35",
    text: "Poznajem ___ već dugo godina.",
    options: ["ga", "mu", "on", "njega"],
    correctAnswer: "ga",
    translation: { en: "I have known him for many years.", ru: "Я знаю его уже много лет.", ua: "Я знаю його вже багато років." },
    level: "A2",
    category: "pronouns",
  },
  {
    id: "fb-36",
    text: "Idem s ___ na koncert.",
    options: ["njom", "joj", "ona", "nje"],
    correctAnswer: "njom",
    translation: { en: "I am going with her to concert.", ru: "Я иду с ней на концерт.", ua: "Я йду з нею на концерт." },
    level: "A2",
    category: "pronouns",
  },

  // CASES & PREPOSITIONS (37-60)
  {
    id: "fb-37",
    text: "Idem u ___ na sat jezika.",
    options: ["školu", "škola", "školom", "škole"],
    correctAnswer: "školu",
    translation: { en: "I am going to school for language class.", ru: "Я иду в школу на урок языка.", ua: "Я йду до школи на урок мови." },
    level: "A1",
    category: "cases",
  },
  {
    id: "fb-38",
    text: "Kava bez ___ nije ukusna.",
    options: ["šećera", "šećer", "šećeru", "šećerom"],
    correctAnswer: "šećera",
    translation: { en: "Coffee without sugar is not tasty.", ru: "Кофе без сахара не вкусный.", ua: "Кава без цукру не смачна." },
    level: "A1",
    category: "cases",
  },
  {
    id: "fb-39",
    text: "Putujem u ___ sljedeći tjedan.",
    options: ["Zagreb", "Zagrebu", "Zagreba", "Zagrebom"],
    correctAnswer: "Zagreb",
    translation: { en: "I am traveling to Zagreb next week.", ru: "Я еду в Загреб на следующей неделе.", ua: "Я їду до Загреба наступного тижня." },
    level: "A1",
    category: "cases",
  },
  {
    id: "fb-40",
    text: "Sjedimo u mirnom ___.",
    options: ["restoranu", "restoran", "restorana", "restoranom"],
    correctAnswer: "restoranu",
    translation: { en: "We sit in a quiet restaurant.", ru: "Мы сидим в тихом ресторане.", ua: "Ми сидимо в тихому ресторані." },
    level: "A2",
    category: "cases",
  },
  {
    id: "fb-41",
    text: "Razgovaram s dobrim ___.",
    options: ["prijateljem", "prijatelj", "prijatelja", "prijatelju"],
    correctAnswer: "prijateljem",
    translation: { en: "I am talking with a good friend.", ru: "Я разговариваю с хорошим другом.", ua: "Я розмовляю з хорошим другом." },
    level: "A2",
    category: "cases",
  },
  {
    id: "fb-42",
    text: "Vraćam se iz ___ kasno navečer.",
    options: ["grada", "grad", "gradu", "gradom"],
    correctAnswer: "grada",
    translation: { en: "I am coming back from town late at night.", ru: "Я возвращаюсь из города поздно вечером.", ua: "Я повертаюся з міста пізно ввечері." },
    level: "A2",
    category: "cases",
  },
  {
    id: "fb-43",
    text: "Daj mi čašu friškog ___.",
    options: ["mlijeka", "mlijeko", "mlijeku", "mlijekom"],
    correctAnswer: "mlijeka",
    translation: { en: "Give me a glass of fresh milk.", ru: "Дай мне стакан свежего молока.", ua: "Дай мені склянку свіжого молока." },
    level: "A2",
    category: "cases",
  },
  {
    id: "fb-44",
    text: "Knjiga leži ___ stolu.",
    options: ["na", "u", "iz", "pod"],
    correctAnswer: "na",
    translation: { en: "Book lies on the table.", ru: "Книга лежит на столе.", ua: "Книга лежить на столі." },
    level: "A1",
    category: "prepositions",
  },
  {
    id: "fb-45",
    text: "Mlijeko je ___ hladnjaku.",
    options: ["u", "na", "za", "kod"],
    correctAnswer: "u",
    translation: { en: "Milk is in the fridge.", ru: "Молоко в холодильнике.", ua: "Молоко в холодильнику." },
    level: "A1",
    category: "prepositions",
  },
  {
    id: "fb-46",
    text: "Idem ___ prijatelja u posjet.",
    options: ["kod", "u", "na", "sa"],
    correctAnswer: "kod",
    translation: { en: "I go to a friend's place for a visit.", ru: "Я иду к другу в гости.", ua: "Я йду до друга в гості." },
    level: "A2",
    category: "prepositions",
  },
  {
    id: "fb-47",
    text: "Sastat ćemo se ___ ručka.",
    options: ["poslije", "iz", "bez", "kroz"],
    correctAnswer: "poslije",
    translation: { en: "We will meet after lunch.", ru: "Мы встретимся после обеда.", ua: "Ми зустрінемося після обіду." },
    level: "A2",
    category: "prepositions",
  },
  {
    id: "fb-48",
    text: "Vlak vozi ___ tunel.",
    options: ["kroz", "na", "u", "pod"],
    correctAnswer: "kroz",
    translation: { en: "The train drives through the tunnel.", ru: "Поезд едет через тоннель.", ua: "Потяг їде через тунель." },
    level: "B1",
    category: "prepositions",
  },
  {
    id: "fb-49",
    text: "Govorimo o novom ___.",
    options: ["projektu", "projekt", "projekta", "projektom"],
    correctAnswer: "projektu",
    translation: { en: "We are talking about new project.", ru: "Мы говорим о новом проекте.", ua: "Ми говоримо про новий проект." },
    level: "B1",
    category: "cases",
  },
  {
    id: "fb-50",
    text: "Unatoč jakom ___, nastavili smo hodati.",
    options: ["vjetru", "vjetar", "vjetra", "vjetrom"],
    correctAnswer: "vjetru",
    translation: { en: "Despite strong wind, we kept walking.", ru: "Несмотря на сильный ветер, мы продолжили идти.", ua: "Незважаючи на сильний вітер, ми продовжили йти." },
    level: "B2",
    category: "cases",
  }
];