export interface VocabWord {
  hr: string;
  en: string;
  ru: string;
  ua: string;
  level: string;
  category: string;
  example?: { hr: string; en: string; ru: string; ua: string };
}

export const vocabularyCategories = [
  "food", "family", "transport", "work", "home", "nature",
  "city", "body", "clothes", "colors", "time", "school",
  "emotions", "sports", "travel",
] as const;

export type VocabCategory = typeof vocabularyCategories[number];

export const categoryLabels: Record<VocabCategory, { en: string; ru: string; ua: string }> = {
  food: { en: "Food & Drinks", ru: "Еда и напитки", ua: "Їжа та напої" },
  family: { en: "Family", ru: "Семья", ua: "Сім'я" },
  transport: { en: "Transport", ru: "Транспорт", ua: "Транспорт" },
  work: { en: "Work & Career", ru: "Работа и карьера", ua: "Робота та кар'єра" },
  home: { en: "Home & House", ru: "Дом и жильё", ua: "Дім та житло" },
  nature: { en: "Nature", ru: "Природа", ua: "Природа" },
  city: { en: "City & Places", ru: "Город и места", ua: "Місто та місця" },
  body: { en: "Body & Health", ru: "Тело и здоровье", ua: "Тіло та здоров'я" },
  clothes: { en: "Clothes", ru: "Одежда", ua: "Одяг" },
  colors: { en: "Colors", ru: "Цвета", ua: "Кольори" },
  time: { en: "Time & Days", ru: "Время и дни", ua: "Час та дні" },
  school: { en: "School & Education", ru: "Школа и образование", ua: "Школа та освіта" },
  emotions: { en: "Emotions", ru: "Эмоции", ua: "Емоції" },
  sports: { en: "Sports & Hobbies", ru: "Спорт и хобби", ua: "Спорт та хобі" },
  travel: { en: "Travel", ru: "Путешествия", ua: "Подорожі" },
};

export const vocabularyWords: VocabWord[] = [
  // ══════ FOOD ══════
  { hr: "kruh", en: "bread", ru: "хлеб", ua: "хліб", level: "A1", category: "food", example: { hr: "Kupujem svježi kruh.", en: "I buy fresh bread.", ru: "Я покупаю свежий хлеб.", ua: "Я купую свіжий хліб." } },
  { hr: "mlijeko", en: "milk", ru: "молоко", ua: "молоко", level: "A1", category: "food" },
  { hr: "voda", en: "water", ru: "вода", ua: "вода", level: "A1", category: "food" },
  { hr: "kava", en: "coffee", ru: "кофе", ua: "кава", level: "A1", category: "food" },
  { hr: "čaj", en: "tea", ru: "чай", ua: "чай", level: "A1", category: "food" },
  { hr: "jabuka", en: "apple", ru: "яблоко", ua: "яблуко", level: "A1", category: "food" },
  { hr: "meso", en: "meat", ru: "мясо", ua: "м'ясо", level: "A1", category: "food" },
  { hr: "riba", en: "fish", ru: "рыба", ua: "риба", level: "A1", category: "food" },
  { hr: "sir", en: "cheese", ru: "сыр", ua: "сир", level: "A1", category: "food" },
  { hr: "jaje", en: "egg", ru: "яйцо", ua: "яйце", level: "A1", category: "food" },
  { hr: "sol", en: "salt", ru: "соль", ua: "сіль", level: "A1", category: "food" },
  { hr: "šećer", en: "sugar", ru: "сахар", ua: "цукор", level: "A1", category: "food" },
  { hr: "juha", en: "soup", ru: "суп", ua: "суп", level: "A1", category: "food" },
  { hr: "salata", en: "salad", ru: "салат", ua: "салат", level: "A1", category: "food" },
  { hr: "pivo", en: "beer", ru: "пиво", ua: "пиво", level: "A2", category: "food" },
  { hr: "vino", en: "wine", ru: "вино", ua: "вино", level: "A2", category: "food" },
  { hr: "voće", en: "fruit", ru: "фрукты", ua: "фрукти", level: "A1", category: "food" },
  { hr: "povrće", en: "vegetables", ru: "овощи", ua: "овочі", level: "A1", category: "food" },
  { hr: "ručak", en: "lunch", ru: "обед", ua: "обід", level: "A1", category: "food" },
  { hr: "večera", en: "dinner", ru: "ужин", ua: "вечеря", level: "A1", category: "food" },
  { hr: "doručak", en: "breakfast", ru: "завтрак", ua: "сніданок", level: "A1", category: "food" },
  { hr: "kolač", en: "cake", ru: "торт/пирожное", ua: "торт/тістечко", level: "A2", category: "food" },
  { hr: "sladoled", en: "ice cream", ru: "мороженое", ua: "морозиво", level: "A2", category: "food" },

  // ══════ FAMILY ══════
  { hr: "otac", en: "father", ru: "отец", ua: "батько", level: "A1", category: "family" },
  { hr: "majka", en: "mother", ru: "мать", ua: "мати", level: "A1", category: "family" },
  { hr: "brat", en: "brother", ru: "брат", ua: "брат", level: "A1", category: "family" },
  { hr: "sestra", en: "sister", ru: "сестра", ua: "сестра", level: "A1", category: "family" },
  { hr: "sin", en: "son", ru: "сын", ua: "син", level: "A1", category: "family" },
  { hr: "kći", en: "daughter", ru: "дочь", ua: "донька", level: "A1", category: "family" },
  { hr: "djed", en: "grandfather", ru: "дедушка", ua: "дідусь", level: "A1", category: "family" },
  { hr: "baka", en: "grandmother", ru: "бабушка", ua: "бабуся", level: "A1", category: "family" },
  { hr: "muž", en: "husband", ru: "муж", ua: "чоловік", level: "A1", category: "family" },
  { hr: "žena", en: "wife/woman", ru: "жена/женщина", ua: "дружина/жінка", level: "A1", category: "family" },
  { hr: "dijete", en: "child", ru: "ребёнок", ua: "дитина", level: "A1", category: "family" },
  { hr: "obitelj", en: "family", ru: "семья", ua: "сім'я", level: "A1", category: "family" },
  { hr: "prijatelj", en: "friend", ru: "друг", ua: "друг", level: "A1", category: "family" },
  { hr: "susjed", en: "neighbor", ru: "сосед", ua: "сусід", level: "A2", category: "family" },

  // ══════ TRANSPORT ══════
  { hr: "auto", en: "car", ru: "автомобиль", ua: "автомобіль", level: "A1", category: "transport" },
  { hr: "autobus", en: "bus", ru: "автобус", ua: "автобус", level: "A1", category: "transport" },
  { hr: "vlak", en: "train", ru: "поезд", ua: "потяг", level: "A1", category: "transport" },
  { hr: "tramvaj", en: "tram", ru: "трамвай", ua: "трамвай", level: "A1", category: "transport" },
  { hr: "avion", en: "airplane", ru: "самолёт", ua: "літак", level: "A1", category: "transport" },
  { hr: "bicikl", en: "bicycle", ru: "велосипед", ua: "велосипед", level: "A1", category: "transport" },
  { hr: "brod", en: "ship", ru: "корабль", ua: "корабель", level: "A2", category: "transport" },
  { hr: "karta", en: "ticket", ru: "билет", ua: "квиток", level: "A1", category: "transport" },
  { hr: "stanica", en: "station", ru: "станция", ua: "станція", level: "A1", category: "transport" },
  { hr: "vozač", en: "driver", ru: "водитель", ua: "водій", level: "A2", category: "transport" },
  { hr: "benzin", en: "gasoline", ru: "бензин", ua: "бензин", level: "A2", category: "transport" },
  { hr: "prometna gužva", en: "traffic jam", ru: "пробка", ua: "затор", level: "B1", category: "transport" },

  // ══════ WORK ══════
  { hr: "posao", en: "job", ru: "работа", ua: "робота", level: "A1", category: "work" },
  { hr: "ured", en: "office", ru: "офис", ua: "офіс", level: "A2", category: "work" },
  { hr: "šef", en: "boss", ru: "начальник", ua: "начальник", level: "A2", category: "work" },
  { hr: "kolega", en: "colleague", ru: "коллега", ua: "колега", level: "A2", category: "work" },
  { hr: "plaća", en: "salary", ru: "зарплата", ua: "зарплата", level: "A2", category: "work" },
  { hr: "sastanak", en: "meeting", ru: "совещание", ua: "нарада", level: "B1", category: "work" },
  { hr: "životopis", en: "CV/resume", ru: "резюме", ua: "резюме", level: "B1", category: "work" },
  { hr: "zapošljavanje", en: "employment", ru: "трудоустройство", ua: "працевлаштування", level: "B1", category: "work" },
  { hr: "poslodavac", en: "employer", ru: "работодатель", ua: "роботодавець", level: "B1", category: "work" },
  { hr: "radnik", en: "worker", ru: "рабочий", ua: "робітник", level: "A2", category: "work" },
  { hr: "iskustvo", en: "experience", ru: "опыт", ua: "досвід", level: "B1", category: "work" },
  { hr: "ugovor", en: "contract", ru: "контракт", ua: "контракт", level: "B1", category: "work" },

  // ══════ HOME ══════
  { hr: "kuća", en: "house", ru: "дом", ua: "будинок", level: "A1", category: "home" },
  { hr: "stan", en: "apartment", ru: "квартира", ua: "квартира", level: "A1", category: "home" },
  { hr: "soba", en: "room", ru: "комната", ua: "кімната", level: "A1", category: "home" },
  { hr: "kuhinja", en: "kitchen", ru: "кухня", ua: "кухня", level: "A1", category: "home" },
  { hr: "kupaonica", en: "bathroom", ru: "ванная", ua: "ванна", level: "A1", category: "home" },
  { hr: "spavaća soba", en: "bedroom", ru: "спальня", ua: "спальня", level: "A1", category: "home" },
  { hr: "stol", en: "table", ru: "стол", ua: "стіл", level: "A1", category: "home" },
  { hr: "stolica", en: "chair", ru: "стул", ua: "стілець", level: "A1", category: "home" },
  { hr: "krevet", en: "bed", ru: "кровать", ua: "ліжко", level: "A1", category: "home" },
  { hr: "prozor", en: "window", ru: "окно", ua: "вікно", level: "A1", category: "home" },
  { hr: "vrata", en: "door", ru: "дверь", ua: "двері", level: "A1", category: "home" },
  { hr: "kat", en: "floor/story", ru: "этаж", ua: "поверх", level: "A2", category: "home" },
  { hr: "stubište", en: "staircase", ru: "лестница", ua: "сходи", level: "A2", category: "home" },

  // ══════ NATURE ══════
  { hr: "more", en: "sea", ru: "море", ua: "море", level: "A1", category: "nature" },
  { hr: "planina", en: "mountain", ru: "гора", ua: "гора", level: "A1", category: "nature" },
  { hr: "rijeka", en: "river", ru: "река", ua: "річка", level: "A1", category: "nature" },
  { hr: "jezero", en: "lake", ru: "озеро", ua: "озеро", level: "A1", category: "nature" },
  { hr: "šuma", en: "forest", ru: "лес", ua: "ліс", level: "A1", category: "nature" },
  { hr: "sunce", en: "sun", ru: "солнце", ua: "сонце", level: "A1", category: "nature" },
  { hr: "kiša", en: "rain", ru: "дождь", ua: "дощ", level: "A1", category: "nature" },
  { hr: "snijeg", en: "snow", ru: "снег", ua: "сніг", level: "A1", category: "nature" },
  { hr: "vjetar", en: "wind", ru: "ветер", ua: "вітер", level: "A2", category: "nature" },
  { hr: "cvijet", en: "flower", ru: "цветок", ua: "квітка", level: "A1", category: "nature" },
  { hr: "stablo", en: "tree", ru: "дерево", ua: "дерево", level: "A1", category: "nature" },
  { hr: "nebo", en: "sky", ru: "небо", ua: "небо", level: "A1", category: "nature" },
  { hr: "otok", en: "island", ru: "остров", ua: "острів", level: "A2", category: "nature" },
  { hr: "plaža", en: "beach", ru: "пляж", ua: "пляж", level: "A2", category: "nature" },

  // ══════ CITY ══════
  { hr: "grad", en: "city", ru: "город", ua: "місто", level: "A1", category: "city" },
  { hr: "ulica", en: "street", ru: "улица", ua: "вулиця", level: "A1", category: "city" },
  { hr: "trg", en: "square", ru: "площадь", ua: "площа", level: "A1", category: "city" },
  { hr: "park", en: "park", ru: "парк", ua: "парк", level: "A1", category: "city" },
  { hr: "bolnica", en: "hospital", ru: "больница", ua: "лікарня", level: "A2", category: "city" },
  { hr: "škola", en: "school", ru: "школа", ua: "школа", level: "A1", category: "city" },
  { hr: "trgovina", en: "shop", ru: "магазин", ua: "магазин", level: "A1", category: "city" },
  { hr: "restoran", en: "restaurant", ru: "ресторан", ua: "ресторан", level: "A1", category: "city" },
  { hr: "crkva", en: "church", ru: "церковь", ua: "церква", level: "A2", category: "city" },
  { hr: "muzej", en: "museum", ru: "музей", ua: "музей", level: "A2", category: "city" },
  { hr: "knjižnica", en: "library", ru: "библиотека", ua: "бібліотека", level: "A2", category: "city" },
  { hr: "pošta", en: "post office", ru: "почта", ua: "пошта", level: "A2", category: "city" },
  { hr: "banka", en: "bank", ru: "банк", ua: "банк", level: "A2", category: "city" },
  { hr: "ljekarna", en: "pharmacy", ru: "аптека", ua: "аптека", level: "A2", category: "city" },

  // ══════ BODY ══════
  { hr: "glava", en: "head", ru: "голова", ua: "голова", level: "A1", category: "body" },
  { hr: "ruka", en: "hand/arm", ru: "рука", ua: "рука", level: "A1", category: "body" },
  { hr: "noga", en: "leg/foot", ru: "нога", ua: "нога", level: "A1", category: "body" },
  { hr: "oko", en: "eye", ru: "глаз", ua: "око", level: "A1", category: "body" },
  { hr: "uho", en: "ear", ru: "ухо", ua: "вухо", level: "A1", category: "body" },
  { hr: "nos", en: "nose", ru: "нос", ua: "ніс", level: "A1", category: "body" },
  { hr: "usta", en: "mouth", ru: "рот", ua: "рот", level: "A1", category: "body" },
  { hr: "srce", en: "heart", ru: "сердце", ua: "серце", level: "A1", category: "body" },
  { hr: "zub", en: "tooth", ru: "зуб", ua: "зуб", level: "A1", category: "body" },
  { hr: "kosa", en: "hair", ru: "волосы", ua: "волосся", level: "A1", category: "body" },
  { hr: "prst", en: "finger", ru: "палец", ua: "палець", level: "A2", category: "body" },
  { hr: "leđa", en: "back", ru: "спина", ua: "спина", level: "A2", category: "body" },

  // ══════ CLOTHES ══════
  { hr: "košulja", en: "shirt", ru: "рубашка", ua: "сорочка", level: "A1", category: "clothes" },
  { hr: "hlače", en: "pants", ru: "брюки", ua: "штани", level: "A1", category: "clothes" },
  { hr: "haljina", en: "dress", ru: "платье", ua: "сукня", level: "A1", category: "clothes" },
  { hr: "cipele", en: "shoes", ru: "обувь", ua: "взуття", level: "A1", category: "clothes" },
  { hr: "jakna", en: "jacket", ru: "куртка", ua: "куртка", level: "A1", category: "clothes" },
  { hr: "kaput", en: "coat", ru: "пальто", ua: "пальто", level: "A2", category: "clothes" },
  { hr: "šešir", en: "hat", ru: "шляпа", ua: "капелюх", level: "A2", category: "clothes" },
  { hr: "čarape", en: "socks", ru: "носки", ua: "шкарпетки", level: "A1", category: "clothes" },
  { hr: "majica", en: "T-shirt", ru: "футболка", ua: "футболка", level: "A1", category: "clothes" },
  { hr: "suknja", en: "skirt", ru: "юбка", ua: "спідниця", level: "A2", category: "clothes" },

  // ══════ COLORS ══════
  { hr: "crven", en: "red", ru: "красный", ua: "червоний", level: "A1", category: "colors" },
  { hr: "plav", en: "blue", ru: "синий", ua: "синій", level: "A1", category: "colors" },
  { hr: "zelen", en: "green", ru: "зелёный", ua: "зелений", level: "A1", category: "colors" },
  { hr: "žut", en: "yellow", ru: "жёлтый", ua: "жовтий", level: "A1", category: "colors" },
  { hr: "bijel", en: "white", ru: "белый", ua: "білий", level: "A1", category: "colors" },
  { hr: "crn", en: "black", ru: "чёрный", ua: "чорний", level: "A1", category: "colors" },
  { hr: "smeđ", en: "brown", ru: "коричневый", ua: "коричневий", level: "A1", category: "colors" },
  { hr: "siv", en: "gray", ru: "серый", ua: "сірий", level: "A2", category: "colors" },
  { hr: "narančast", en: "orange", ru: "оранжевый", ua: "помаранчевий", level: "A2", category: "colors" },
  { hr: "ljubičast", en: "purple", ru: "фиолетовый", ua: "фіолетовий", level: "A2", category: "colors" },
  { hr: "ružičast", en: "pink", ru: "розовый", ua: "рожевий", level: "A2", category: "colors" },

  // ══════ TIME ══════
  { hr: "danas", en: "today", ru: "сегодня", ua: "сьогодні", level: "A1", category: "time" },
  { hr: "sutra", en: "tomorrow", ru: "завтра", ua: "завтра", level: "A1", category: "time" },
  { hr: "jučer", en: "yesterday", ru: "вчера", ua: "вчора", level: "A1", category: "time" },
  { hr: "sada", en: "now", ru: "сейчас", ua: "зараз", level: "A1", category: "time" },
  { hr: "sat", en: "hour/clock", ru: "час/часы", ua: "година/годинник", level: "A1", category: "time" },
  { hr: "tjedan", en: "week", ru: "неделя", ua: "тиждень", level: "A1", category: "time" },
  { hr: "mjesec", en: "month", ru: "месяц", ua: "місяць", level: "A1", category: "time" },
  { hr: "godina", en: "year", ru: "год", ua: "рік", level: "A1", category: "time" },
  { hr: "ponedjeljak", en: "Monday", ru: "понедельник", ua: "понеділок", level: "A1", category: "time" },
  { hr: "utorak", en: "Tuesday", ru: "вторник", ua: "вівторок", level: "A1", category: "time" },
  { hr: "srijeda", en: "Wednesday", ru: "среда", ua: "середа", level: "A1", category: "time" },
  { hr: "četvrtak", en: "Thursday", ru: "четверг", ua: "четвер", level: "A1", category: "time" },
  { hr: "petak", en: "Friday", ru: "пятница", ua: "п'ятниця", level: "A1", category: "time" },
  { hr: "subota", en: "Saturday", ru: "суббота", ua: "субота", level: "A1", category: "time" },
  { hr: "nedjelja", en: "Sunday", ru: "воскресенье", ua: "неділя", level: "A1", category: "time" },

  // ══════ SCHOOL ══════
  { hr: "učenik", en: "student (school)", ru: "ученик", ua: "учень", level: "A1", category: "school" },
  { hr: "student", en: "student (uni)", ru: "студент", ua: "студент", level: "A1", category: "school" },
  { hr: "profesor", en: "professor", ru: "профессор", ua: "професор", level: "A1", category: "school" },
  { hr: "učitelj", en: "teacher", ru: "учитель", ua: "вчитель", level: "A1", category: "school" },
  { hr: "knjiga", en: "book", ru: "книга", ua: "книга", level: "A1", category: "school" },
  { hr: "bilježnica", en: "notebook", ru: "тетрадь", ua: "зошит", level: "A1", category: "school" },
  { hr: "olovka", en: "pencil", ru: "карандаш", ua: "олівець", level: "A1", category: "school" },
  { hr: "ispit", en: "exam", ru: "экзамен", ua: "іспит", level: "A2", category: "school" },
  { hr: "ocjena", en: "grade", ru: "оценка", ua: "оцінка", level: "A2", category: "school" },
  { hr: "zadaća", en: "homework", ru: "домашнее задание", ua: "домашнє завдання", level: "A2", category: "school" },
  { hr: "sveučilište", en: "university", ru: "университет", ua: "університет", level: "A2", category: "school" },

  // ══════ EMOTIONS ══════
  { hr: "sretan", en: "happy", ru: "счастливый", ua: "щасливий", level: "A1", category: "emotions" },
  { hr: "tužan", en: "sad", ru: "грустный", ua: "сумний", level: "A1", category: "emotions" },
  { hr: "ljut", en: "angry", ru: "злой", ua: "злий", level: "A1", category: "emotions" },
  { hr: "umoran", en: "tired", ru: "усталый", ua: "втомлений", level: "A1", category: "emotions" },
  { hr: "gladan", en: "hungry", ru: "голодный", ua: "голодний", level: "A1", category: "emotions" },
  { hr: "žedan", en: "thirsty", ru: "жаждущий", ua: "спраглий", level: "A1", category: "emotions" },
  { hr: "zaljubljen", en: "in love", ru: "влюблённый", ua: "закоханий", level: "A2", category: "emotions" },
  { hr: "ponosan", en: "proud", ru: "гордый", ua: "гордий", level: "A2", category: "emotions" },
  { hr: "zabrinut", en: "worried", ru: "обеспокоенный", ua: "стурбований", level: "B1", category: "emotions" },
  { hr: "iznenađen", en: "surprised", ru: "удивлённый", ua: "здивований", level: "A2", category: "emotions" },

  // ══════ SPORTS ══════
  { hr: "nogomet", en: "football/soccer", ru: "футбол", ua: "футбол", level: "A1", category: "sports" },
  { hr: "košarka", en: "basketball", ru: "баскетбол", ua: "баскетбол", level: "A2", category: "sports" },
  { hr: "tenis", en: "tennis", ru: "теннис", ua: "теніс", level: "A2", category: "sports" },
  { hr: "plivanje", en: "swimming", ru: "плавание", ua: "плавання", level: "A2", category: "sports" },
  { hr: "trčanje", en: "running", ru: "бег", ua: "біг", level: "A2", category: "sports" },
  { hr: "skijanje", en: "skiing", ru: "лыжи", ua: "лижі", level: "A2", category: "sports" },
  { hr: "planinarenje", en: "hiking", ru: "пеший туризм", ua: "пішохідний туризм", level: "B1", category: "sports" },
  { hr: "veslanje", en: "rowing", ru: "гребля", ua: "веслування", level: "B1", category: "sports" },

  // ══════ TRAVEL ══════
  { hr: "putovanje", en: "journey/trip", ru: "путешествие", ua: "подорож", level: "A2", category: "travel" },
  { hr: "putovnica", en: "passport", ru: "паспорт", ua: "паспорт", level: "A2", category: "travel" },
  { hr: "hotel", en: "hotel", ru: "отель", ua: "готель", level: "A1", category: "travel" },
  { hr: "aerodrom", en: "airport", ru: "аэропорт", ua: "аеропорт", level: "A2", category: "travel" },
  { hr: "luka", en: "port/harbor", ru: "порт", ua: "порт", level: "A2", category: "travel" },
  { hr: "turizam", en: "tourism", ru: "туризм", ua: "туризм", level: "A2", category: "travel" },
  { hr: "vodič", en: "guide", ru: "гид", ua: "гід", level: "B1", category: "travel" },
  { hr: "rezervacija", en: "reservation", ru: "бронирование", ua: "бронювання", level: "B1", category: "travel" },
  { hr: "suvenir", en: "souvenir", ru: "сувенир", ua: "сувенір", level: "A2", category: "travel" },
  { hr: "razgledavanje", en: "sightseeing", ru: "осмотр достопримечательностей", ua: "огляд визначних місць", level: "B1", category: "travel" },
];
