export const levels=['A1','A2','B1','B2','C1','C2'];
export const levelNames={ru:['Первые слова','Повседневная жизнь','Свобода общения','Новые горизонты','Точность мысли','Без границ'],en:['First words','Everyday life','Speak freely','New horizons','Precise expression','Without limits'],uk:['Перші слова','Повсякденне життя','Свобода спілкування','Нові горизонти','Точність думки','Без меж'],hr:['Prve riječi','Svakodnevni život','Sloboda razgovora','Novi horizonti','Precizno izražavanje','Bez granica']};
export const words=[
 ['bok','привет','hello','привіт','Фразы'],['hvala','спасибо','thank you','дякую','Фразы'],['more','море','sea','море','Природа'],['kava','кофе','coffee','кава','Еда и напитки'],['voda','вода','water','вода','Еда и напитки'],['kuća','дом','house','будинок','Дом и жильё'],['grad','город','city','місто','Город и места'],['knjiga','книга','book','книга','Школа и образование'],['prijatelj','друг','friend','друг','Семья'],['sunce','солнце','sun','сонце','Природа'],['dobro','хорошо','well','добре','Фразы'],['putovanje','путешествие','journey','подорож','Путешествия'],['kruh','хлеб','bread','хліб','Еда и напитки'],['otok','остров','island','острів','Природа'],['posao','работа','work','робота','Работа и карьера'],['vrijeme','время','time','час','Время и дни'],['obitelj','семья','family','родина','Семья'],['vlak','поезд','train','потяг','Транспорт'],['učiti','учить','learn','вчити','Глаголы'],['lijep','красивый','beautiful','гарний','Прилагательные']
].map((w,i)=>({id:String(i+1),hr:w[0],ru:w[1],en:w[2],uk:w[3],topic:w[4],level:i>14?'A2':'A1',type:i===18?'Глаголы':i===19?'Прилагательные':'Существительные'}));
export const topics=['Еда и напитки','Семья','Транспорт','Работа и карьера','Дом и жильё','Природа','Город и места','Тело и здоровье','Одежда','Цвета','Время и дни','Школа и образование','Эмоции','Спорт и хобби','Путешествия','Глаголы','Прилагательные','Наречия','Фразы','Числа','Предлоги'];
const lessonTitles=[['Личные местоимения','Глагол biti и знакомство','В кафе','Основные приветствия'],['Винительный падеж','Прошедшее время','В ресторане','Магазин и покупки'],['Вид глагола','Будущее время','Жизнь у моря','Выражаем мнение'],['Условное наклонение','Пассивный залог','Работа и карьера','Язык новостей'],['Сложные предложения','Союзы и оттенки смысла','Культура общения','Литература'],['Фразеологизмы','Стиль и точность','Общество и дискуссия','Итоговая практика']];
export const lessons=levels.flatMap((level,l)=>lessonTitles[l].map((title,i)=>({id:`${level.toLowerCase()}-${i===2?'reading':i===3?'dictation':'grammar'}-${i+1}`,title,level,index:i,type:i===2?'Чтение':i===3?'Диктант':'Грамматика',minutes:8+i*2,xp:50})));
export const gameDefs=[['word-match','Подбор слов','Найдите пары слов и переводов','Layers',20],['fill-blanks','Заполни пропуски','Подберите слово к предложению','TextCursorInput',30],['scramble','Собери слово','Расставьте буквы по местам','Puzzle',25],['hangman','Виселица','Угадайте слово за шесть попыток','PenLine',15],['speed-quiz','Быстрый тест','Переводите слова на время','Zap',50],['reading','Чтение','Истории, которые приближают Хорватию','BookOpen',35],['listening','Аудирование','Услышьте, как звучит язык','Headphones',40],['audio-spelling','Аудио-диктант','Запишите слово на слух','AudioLines',45]].map(([id,title,desc,icon,xp])=>({id,title,desc,icon,xp}));
export const grammarTopics=['Хорватский алфавит','Правила произношения','Ударения','Звуковые чередования','Именительный падеж','Родительный падеж','Дательный падеж','Винительный падеж','Звательный падеж','Местный падеж','Творительный падеж','Сводная таблица падежей','Число существительных','Отсутствие артиклей','Глаголы','Числительные','Повседневные темы','Местоимения и предлоги','Продвинутая грамматика'];
export const articles=[{id:'split',title:'Утро в Сплите',hrTitle:'Jutro u Splitu',level:'A1',desc:'Маленькие ритуалы у большого моря',body:'Bok! Ja sam Ana. Živim u Splitu. Svako jutro pijem kavu uz more. Moj prijatelj Marko čita knjigu. Sunce je toplo. Danas učimo hrvatski zajedno.',ru:'Привет! Я Ана. Я живу в Сплите. Каждое утро пью кофе у моря. Мой друг Марко читает книгу. Солнце тёплое. Сегодня мы вместе учим хорватский.',en:'Hi! I am Ana. I live in Split. Every morning I drink coffee by the sea. My friend Marko reads a book. The sun is warm. Today we learn Croatian together.',uk:'Привіт! Я Ана. Я живу в Спліті. Щоранку п’ю каву біля моря. Мій друг Марко читає книгу. Сонце тепле. Сьогодні ми разом вчимо хорватську.'},{id:'plitvice',title:'По тропам Плитвиц',hrTitle:'Put kroz prirodu',level:'A2',desc:'Неспешная прогулка среди озёр',body:'Danas idemo u prirodu. Put vodi do jezera. Voda je hladna i čista. Slušamo ptice i razgovaramo. Nakon šetnje pijemo vodu i jedemo kruh.',ru:'Сегодня мы идём на природу. Дорога ведёт к озеру. Вода холодная и чистая. Мы слушаем птиц и разговариваем. После прогулки пьём воду и едим хлеб.',en:'Today we go into nature. The path leads to a lake. The water is cold and clear. We listen to birds and talk. After the walk we drink water and eat bread.',uk:'Сьогодні ми йдемо на природу. Дорога веде до озера. Вода холодна й чиста. Ми слухаємо птахів і розмовляємо. Після прогулянки п’ємо воду та їмо хліб.'}];
export const achievementCategories=['Словарь','Серия дней','Уроки и уровни','Опыт XP','Мини-игры','AI-наставник','Секретные'];
export const achievements=['Первое слово','Первые шаги','Неделя открытий','Урок за уроком','Новый уровень','Первая сотня XP','Время играть','Хороший собеседник','Мастер повторения','Точный перевод','Секрет острова','Без границ'].map((title,i)=>({id:i,title,category:achievementCategories[i%7],rarity:['Обычное','Редкое','Эпическое','Легендарное'][i%4],target:(i+1)*5,xp:(i+1)*25}));
export const initialState={name:'Алекс',role:'student',signed:false,goal:15,days:['Пн','Ср','Пт'],view:'Острова',completed:[],favorites:['3','4'],learned:[],xp:120,coins:40,plan:'Start',level:'A1',reminders:false,news:[{id:'welcome',version:'0.1',title:'Новая глава вашего обучения',body:'Добро пожаловать в Croatian Mentor. Выберите свой ритм, откройте первый урок и начните знакомство с хорватским.',published:true,date:'2026-09-13',translations:{}}],events:[],messages:[],dailyDone:false};
export function loadState(){try{return {...initialState,...JSON.parse(localStorage.getItem('cm-demo')||'{}')}}catch{return initialState}}
